# Generated by Django 3.2.9 on 2021-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
