# Generated by Django 3.2.9 on 2021-11-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211128_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProduct',
        ),
    ]
